version: "3"
services:
  cloudflared:
    container_name: cloudflared
    image: sancraftdev/cloudflared:latest
#    image: sancraftdev/cloudflared:develop
    restart: always
    network_mode: host
    environment:
      - "token=your-cloudflared-tunnel-token"
